### PR TITLE
Add config to deno example benchmarks

### PR DESCRIPTION
**Pull request by sSelmann**
# Pull Request type
- [x] Refactor
- [x] Documentation

This PR aims to enhance code readability in benchmarks by adding configuration. Additionally, it allows users to easily change the submission address, crucial when Alice lacks sufficient balance to run benchmarks. With this change, the account can be modified from config.ts.

## Testing Performed
I performed manual testing, and I did not receive any errors when I ran all the benchmarks, and they started and finished successfully.

## Checklist
- [x] I have performed a self-review of my own code.
- [x] The tests pass successfully with `cargo test`.
- [x] The code was formatted with `cargo fmt`.
- [x] The code compiles with no new warnings with `cargo build --release` and `cargo build --release --features runtime-benchmarks`.
- [x] The code has no error when using `deno run -A ./examples/deno/benchmarks/query_rows.ts` and other benchmark files.
- [x] The code has no new warnings when using `cargo clippy`.
- [ ] If this change affects documented features or needs new documentation, I have created a PR with a [documentation update](https://github.com/availproject/availproject.github.io).

### CODE REVIEW

**Comment by Leouarz** [comment]
Hey @sSelmann Thank you for your contribution. 
Please refer to this configuration file to make naming consistent : https://github.com/availproject/avail/blob/main/avail-js/examples/config.ts
Also be careful about casing in the config.

**Comment by sSelmann** [comment]
Hi @Leouarz Thanks for your comment. I made edits based on the config you refered. However, I moved the config to the deno folder instead of benchmarks and integrated the config within the examples. So the config currently works for all deno examples, not just benchmarks.

**Comment by markopoloparadox** [comment]
@sSelmann 
Could you undo your last change? The Deno examples are supposed to be self-sufficient and should not have any config file attached to them.

**Comment by sSelmann** [comment]
Hi @markopoloparadox 
As you said, I undo the last changes and only added the configuration to the benchmarks.

**Review by Leouarz — APPROVED** [review]

**Pull request merged**
