### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by th3nyst1c**
Fixed two broken links

# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- [ ] Feature
- [ ] Bugfix
- [ ] Refactor
- [ ] Format
- [x] Documentation
- [ ] Testing
- [ ] Other:

## Checklist
- [ ] I have performed a self-review of my own code.
- [ ] The tests pass successfully with `cargo test`.
- [ ] The code was formatted with `cargo fmt`.
- [ ] The code compiles with no new warnings with `cargo build --release` and `cargo build --release --features runtime-benchmarks`.
- [ ] The code has no new warnings when using `cargo clippy`.
- [ ] If this change affects documented features or needs new documentation, I have created a PR with a [documentation update](https://github.com/availproject/availproject.github.io).

### CODE REVIEW

**Comment by markopoloparadox** [comment]
Your history shows bot-like activity. Closing because we don't merge PRs created by bots.

**Comment by th3nyst1c** [comment]
Wow. This seems like a useless excuse. If the fix is useful, why not accept the commit? I really don't understand.

**Comment by th3nyst1c** [comment]
Furthermore, your comment is offensive. I'm just trying to be useful to the projects that interest me most, and since I haven't programmed for a long time I'm trying to do it by correcting the documentation.

**Comment by th3nyst1c** [comment]
Fixing the documentation means I go read it and learn something new. The correction is only a side effect which however is useful to the project. No bots here, man.

**Comment by th3nyst1c** [comment]
Regardless of what happened, I will continue to read the documentation. I must say that Avail is truly innovative and therefore even if it is really difficult to understand everything, it is still interesting to sift through documentation and code fragments. However, I have a question: if I find typos, broken links or other similar errors, can't I correct them because I look like a bot?

**Pull request closed without merging**
